title: Overwitch
author:
  name: David García Goñi
  email: "dagargo@gmail.com"
description: JACK client for Overbridge devices
baseurl: "/overwitch/"
url: "https://dagargo.github.io/overwitch/"

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/dagargo" }

header_pages:
  - installation.md
  - usage.md
  - configuration.md
  - adding.md
